[Sprint4][Team3][Task3]-Implement headless Chrome test for React UI for /users/{user_id}
North-Seattle-College/ad440-winter2021-tuesday-repo pull request #242
Opened 2021-03-01 01:52 UTC by OyunominJuno

2021-03-01 07:57 UTC, asiagromasia commented on testing/ui-tests/ui-test-users-userid.js
> +      await page.screenshot({path: '../results/ad440-users-46-screenshot' + stringDate + '.png'});
let's double check if we should store the screenshots in this folder

2021-03-01 08:02 UTC, asiagromasia reviewed
removing the brackets from the repo name would be beneficial

2021-03-02 02:41 UTC, sunshinejen requested changes
Looks great Juno! Any reason why there are so many files being changed? Are those Dereks changes? If so, maybe only once he is done those should be merged.

2021-03-05 00:50 UTC, sunshinejen approved these changes

2021-03-05 01:06 UTC, merged