Automationspn
North-Seattle-College/ad440-winter2021-tuesday-repo pull request #29
Opened 2021-01-16 23:54 UTC by selinapn

2021-01-17 03:20 UTC, toddysm requested changes, later dismissed

2021-01-17 03:20 UTC, toddysm commented on automationspn/azuredeploy.json
> +{
The folder structure we discussed was:
```
/ (root)
/automation
/automation/functions
```
the `azuredeploy.json` and the `script.ps1` files should be in the `/automation/functions` folder. Structuring your files in an intuitive and logical way will help you better manage the source code when it grows and when you have more people and teams involved.

2021-01-17 03:20 UTC, toddysm commented on automationspn/script.ps1
> +func init $foldername --powershell
This part actually creates a function (and generates code) on your local machine. This is a separate task. You should remove that

2021-01-17 03:20 UTC, toddysm commented on automationspn/script.ps1
> +$location = 'West US 2'
Hard coding the location is not recommended. What if the automation is used to create a function in a different location.

2021-01-17 03:20 UTC, toddysm commented on automationspn/script.ps1
> +func new --name $functionname --template "HTTP trigger" --authlevel "anonymous"
Same here - this part creates a function (and generates code) on your local machine. This is a separate task. You should remove that

2021-01-17 03:20 UTC, toddysm commented on automationspn/script.ps1
> +func start
This starts the local function (on your machine) and is not needed for the resource automation.

2021-01-17 03:20 UTC, toddysm commented on automationspn/script.ps1
> +$templateUri = "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-function-app-create-dynamic/azuredeploy.json"
I assume this is the URL you mentioned in Slack? This should point to your `azuredeploy.json`. What is the URL you should use?

2021-01-19 07:08 UTC, vq37vhr approved these changes
Looks good to me!!

2021-01-19 07:15 UTC, Pabriones approved these changes
saw the changes.. Looks good

2021-01-19 22:08 UTC, jlsnow301 approved these changes
Merge conflicts (not your fault in this case) can probably be ignored here

2021-01-21 03:03 UTC, merged