pk sprint1 task2
North-Seattle-College/ad440-winter2021-tuesday-repo pull request #36
Opened 2021-01-19 06:14 UTC by socolorphil

fairly confident the logic is sound and that it would connect to the db. running shows functions as implemented. but cannot debug issues around pyodbc package on local machine...

2021-01-19 20:29 UTC, RealDogDad submitted a review, later dismissed
Please add your .vscode/ dir to your .gitignore and request reviews again.

2021-01-19 22:16 UTC, jlsnow301 requested changes

2021-01-19 22:16 UTC, jlsnow301 commented on .gitignore
> +.venv
Just click the lil commit button 
```suggestion
.venv
.vscode/
```

2021-01-20 00:40 UTC, All-Schuck-Up reviewed
Looks good with recommended changes to gitignore

2021-01-20 07:35 UTC, jlsnow301 approved these changes
should be okay once merge conflicts are resolved

2021-01-21 18:27 UTC, merged