Pk sprint2 task2
North-Seattle-College/ad440-winter2021-tuesday-repo pull request #85
Opened 2021-01-31 21:15 UTC by socolorphil

added console logging to init.py files for {userId} methods

2021-02-01 19:02 UTC, Raotrux commented
The logging itself looks good but where are all of these other changes coming from? I have no idea what's going on with most of that, it seems like other people's tasks, so I'm hesitant to approve.

2021-02-01 22:20 UTC, RealDogDad commented on automation/functions/script.ps1
> +$templateUri = "https://raw.githubusercontent.com/selinapn/ad440-winter2021-tuesday-repo/automationspn-s2/automation/functions/azuredeploy.json"
Is this handled by Deploy team?

2021-02-01 22:28 UTC, RealDogDad reviewed
Just wondering if Team Deploy is to handle the URIs for Azure Resouces. Otherwise you did what I did. Although maybe it would be smart to set a logging configuration somewhere. I used a python dict for a config,.

2021-02-01 22:29 UTC, RealDogDad approved these changes
Should we add a dict for logging configuration for easy changes later?

2021-02-02 21:45 UTC, jlsnow301 requested changes
Looks like some merge artefacts going on. Please merge in upstream dev again, some of these files shouldn't be here

2021-02-02 22:25 UTC, jlsnow301 approved these changes
ok great

2021-02-02 22:25 UTC, merged